spring.application.name=feniks-build-demo
spring.datasource.url=jdbc:h2:file:./data/feniks-demo
spring.sql.init.mode=never
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true
spring.h2.console.enabled=false
server.address=127.0.0.1
server.port=8080
server.shutdown=graceful
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-trailing-tokens=true
spring.jackson.deserialization.fail-on-numbers-for-enums=true
