CREATE TABLE cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(11) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT cases_positive_id CHECK (id > 0),
    CONSTRAINT cases_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT cases_valid_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'CLOSED', 'CANCELLED'))
);
